{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "veyra.fullname" . }}-api
  labels:
    {{- include "veyra.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "veyra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "veyra.fullname" . }}-frontend
  labels:
    {{- include "veyra.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "veyra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
