apiVersion: v1
kind: Service
metadata:
  name: vra-api-service
  namespace: veyra
  labels:
    app: vra-api
spec:
  type: ClusterIP
  selector:
    app: vra-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vra-frontend-service
  namespace: veyra
  labels:
    app: vra-frontend
spec:
  type: ClusterIP
  selector:
    app: vra-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
